### ISSUE TITLE
laravel blade templating engine

### ISSUE THREAD

**Issue by laravelish** [wordplate/framework#38]
integrate laravel blade template engine https://github.com/jenssegers/blade ?

and how can i integrate whoops ?

**Comment by vinkla** [comment]
If you want to use Blade I suggest you to look at [Bladerunner](https://github.com/ekandreas/bladerunner) by @ekandreas. It provides full Laravel Blade syntax support.

For Whoops I don't know a good solution. We tried integrating Whoops in earlier version but since it was hard to hook into WordPress error handler the UI kept breaking. If you find any good solution please write us back because we would really like to see it integrated.
